import { Router } from "express";
import { hashPassword, normalizeEmail } from "../auth/service.js";
import { ROLE_CODES, type RoleCode } from "../auth/types.js";

const include = { role: true, department: true };
const publicUser = (user: any) => ({ id: user.user_id, name: user.full_name, email: user.email, role: { id: user.role.role_id, code: user.role.role_code, name: user.role.role_name }, department: user.department ? { id: user.department.department_id, name: user.department.department_name, code: user.department.department_code } : null, status: user.status, createdAt: user.created_at, updatedAt: user.updated_at });
const passwordIsValid = (password: unknown) => typeof password === "string" && password.length >= 12;
async function roleAndDepartment(tx: any, roleId: unknown, departmentId: unknown) {
  const role = await tx.role.findUnique({ where: { role_id: Number(roleId) } });
  if (!role || !ROLE_CODES.includes(role.role_code as RoleCode)) throw new Error("INVALID_ROLE");
  const department = departmentId ? await tx.department.findUnique({ where: { department_id: Number(departmentId) } }) : null;
  if (departmentId && !department) throw new Error("INVALID_DEPARTMENT");
  if (role.role_code === "DEPARTMENT_HEAD" && !department) throw new Error("HEAD_DEPARTMENT_REQUIRED");
  return { role, department };
}
export function createUsersRouter(prisma: any) {
  const router = Router();
  router.get("/options", async (_req, res) => { const [roles, departments] = await Promise.all([prisma.role.findMany({ where: { role_code: { in: [...ROLE_CODES] } }, select: { role_id: true, role_code: true, role_name: true }, orderBy: { role_name: "asc" } }), prisma.department.findMany({ select: { department_id: true, department_name: true, department_code: true }, orderBy: { department_name: "asc" } })]); res.json({ ok: true, roles: roles.map((role: any) => ({ id: role.role_id, code: role.role_code, name: role.role_name })), departments: departments.map((department: any) => ({ id: department.department_id, name: department.department_name, code: department.department_code })) }); });
  // Teacher records are rental borrowers, not MIIT Store login accounts. Only
  // roles with an approved application role_code appear in User Management.
  router.get("/", async (req, res) => { const query = typeof req.query.query === "string" ? req.query.query.trim() : "", roleId = Number(req.query.roleId), departmentId = Number(req.query.departmentId), status = typeof req.query.status === "string" ? req.query.status : ""; const users = await prisma.users.findMany({ where: { role: { role_code: { in: [...ROLE_CODES] } }, ...(query ? { OR: [{ full_name: { contains: query } }, { email: { contains: query } }] } : {}), ...(Number.isInteger(roleId) && roleId > 0 ? { role_id: roleId } : {}), ...(Number.isInteger(departmentId) && departmentId > 0 ? { department_id: departmentId } : {}), ...(status === "Active" || status === "Inactive" ? { status } : {}) }, include, orderBy: { full_name: "asc" } }); res.json({ ok: true, users: users.map(publicUser) }); });
  router.post("/", async (req, res) => { const name = typeof req.body.name === "string" ? req.body.name.trim() : "", email = normalizeEmail(req.body.email), password = req.body.password; if (!name || !email || !passwordIsValid(password)) return res.status(400).json({ ok: false, message: "Name, a valid email, and a password of at least 12 characters are required" }); try { const user = await prisma.$transaction(async (tx: any) => { const { role, department } = await roleAndDepartment(tx, req.body.roleId, req.body.departmentId); const username = email; const data: any = { full_name: name, username, email, password_hash: await hashPassword(password), role_id: role.role_id, department_id: department?.department_id ?? null, department_head_of_id: role.role_code === "DEPARTMENT_HEAD" ? department!.department_id : null, status: req.body.status === "Inactive" ? "Inactive" : "Active" }; return tx.users.create({ data, include }); }); res.status(201).json({ ok: true, user: publicUser(user) }); } catch (error) { const message = error instanceof Error ? error.message : ""; res.status(message === "INVALID_ROLE" || message === "INVALID_DEPARTMENT" || message === "HEAD_DEPARTMENT_REQUIRED" ? 400 : 409).json({ ok: false, message: message === "HEAD_DEPARTMENT_REQUIRED" ? "Department heads must have a department" : message === "INVALID_ROLE" || message === "INVALID_DEPARTMENT" ? "Select a valid role and department" : "Email is already in use" }); } });
  router.put("/:id", async (req, res) => { const id = Number(req.params.id), name = typeof req.body.name === "string" ? req.body.name.trim() : "", email = normalizeEmail(req.body.email); if (!Number.isInteger(id) || !name || !email) return res.status(400).json({ ok: false, message: "Valid user details are required" }); if (req.auth?.id === id && req.body.status === "Inactive") return res.status(400).json({ ok: false, message: "You cannot disable your own account" }); try { const user = await prisma.$transaction(async (tx: any) => { const existing = await tx.users.findUnique({ where: { user_id: id }, include }); if (!existing) throw new Error("NOT_FOUND"); const { role, department } = await roleAndDepartment(tx, req.body.roleId, req.body.departmentId); const changingLastAdmin = existing.role.role_code === "ADMIN" && existing.status === "Active" && (role.role_code !== "ADMIN" || req.body.status === "Inactive"); if (changingLastAdmin && await tx.users.count({ where: { status: "Active", role: { role_code: "ADMIN" } } }) <= 1) throw new Error("LAST_ADMIN"); return tx.users.update({ where: { user_id: id }, data: { full_name: name, email, username: email, role_id: role.role_id, department_id: department?.department_id ?? null, department_head_of_id: role.role_code === "DEPARTMENT_HEAD" ? department!.department_id : null, status: req.body.status === "Inactive" ? "Inactive" : "Active" }, include }); }); res.json({ ok: true, user: publicUser(user) }); } catch (error) { const code = error instanceof Error ? error.message : ""; res.status(code === "NOT_FOUND" ? 404 : code === "LAST_ADMIN" ? 400 : code.startsWith("INVALID") || code === "HEAD_DEPARTMENT_REQUIRED" ? 400 : 409).json({ ok: false, message: code === "LAST_ADMIN" ? "At least one active administrator is required" : code === "NOT_FOUND" ? "User not found" : code === "HEAD_DEPARTMENT_REQUIRED" ? "Department heads must have a department" : "Unable to update user" }); } });
  router.post("/:id/reset-password", async (req, res) => { const id = Number(req.params.id), password = req.body.password; if (!Number.isInteger(id) || !passwordIsValid(password)) return res.status(400).json({ ok: false, message: "Password must be at least 12 characters" }); const updated = await prisma.$transaction(async (tx: any) => { const user = await tx.users.findUnique({ where: { user_id: id } }); if (!user) return null; await tx.users.update({ where: { user_id: id }, data: { password_hash: await hashPassword(password) } }); await tx.refresh_token.updateMany({ where: { user_id: id, revoked_at: null }, data: { revoked_at: new Date() } }); return true; }); return updated ? res.json({ ok: true, message: "Password reset and active sessions revoked" }) : res.status(404).json({ ok: false, message: "User not found" }); });
  router.delete("/:id", async (req, res) => { const id = Number(req.params.id); if (!Number.isInteger(id)) return res.status(400).json({ ok: false, message: "Invalid user" }); if (req.auth?.id === id) return res.status(400).json({ ok: false, message: "You cannot delete your own account" }); try { await prisma.$transaction(async (tx: any) => { const user = await tx.users.findUnique({ where: { user_id: id }, include }); if (!user) throw new Error("NOT_FOUND"); if (user.role.role_code === "ADMIN" && user.status === "Active" && await tx.users.count({ where: { status: "Active", role: { role_code: "ADMIN" } } }) <= 1) throw new Error("LAST_ADMIN"); const references = await Promise.all([tx.laptop_rental.count({ where: { OR: [{ issued_by: id }, { teacher_user_id: id }] } }), tx.transfer.count({ where: { OR: [{ initiated_by: id }, { received_by: id }] } })]); if (references.some((count: number) => count > 0)) throw new Error("REFERENCED"); await tx.users.delete({ where: { user_id: id } }); }); return res.json({ ok: true, message: "User deleted" }); } catch (error) { const code = error instanceof Error ? error.message : ""; return res.status(code === "NOT_FOUND" ? 404 : 400).json({ ok: false, message: code === "NOT_FOUND" ? "User not found" : code === "LAST_ADMIN" ? "At least one active administrator is required" : code === "REFERENCED" ? "This user has rental or transfer records and cannot be deleted" : "Unable to delete user" }); } });
  return router;
}
