import { useEffect, useState } from "react";
import { Pencil, Plus, Search, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
const API=import.meta.env.VITE_API_BASE_URL??"http://localhost:5000";
type Department={id:number;name:string}; type Teacher={id:number;name:string;email:string;phone:string;departmentId:number;department:string;laptopStatus?:string};
const blank={name:"",email:"",phone:"",departmentId:""};
export default function TeacherListModal({open,onOpenChange}:{open:boolean;onOpenChange:(v:boolean)=>void}) {
 const [teachers,setTeachers]=useState<Teacher[]>([]),[departments,setDepartments]=useState<Department[]>([]),[draft,setDraft]=useState(blank),[editing,setEditing]=useState<number|null>(null),[query,setQuery]=useState(""),[message,setMessage]=useState("");
 const load=async()=>{const [a,b]=await Promise.all([fetch(API+"/api/teachers").then(r=>r.json()),fetch(API+"/api/departments").then(r=>r.json())]);setTeachers(a.teachers??[]);setDepartments((b.departments??[]).map((x:any)=>({id:x.id??x.department_id,name:x.department})));};
 useEffect(()=>{if(open){void load();setMessage("")}},[open]);
 const save=async()=>{const url=editing?API+"/api/teachers/"+editing:API+"/api/teachers";const r=await fetch(url,{method:editing?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...draft,departmentId:Number(draft.departmentId)})});const p=await r.json();if(!r.ok)return setMessage(p.message??"Unable to save teacher.");setDraft(blank);setEditing(null);setMessage("Teacher saved.");void load();};
 const remove=async(id:number)=>{if(!window.confirm("Delete this teacher?"))return;const r=await fetch(API+"/api/teachers/"+id,{method:"DELETE"});const p=await r.json();if(!r.ok)return setMessage(p.message??"Unable to delete teacher.");void load();};
 const shown=teachers.filter(x=>(x.name+" "+x.email+" "+x.phone+" "+x.department).toLowerCase().includes(query.toLowerCase()));
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[92vh] w-[96vw] max-w-[96vw] overflow-y-auto sm:max-w-[min(96vw,1100px)]"><DialogHeader><DialogTitle>Teacher List</DialogTitle><p className="text-sm text-slate-500">Add teachers here; they will appear immediately in Issue Rental → Teacher.</p></DialogHeader><div className="grid gap-4 lg:grid-cols-[310px_1fr]"><div className="space-y-3 rounded-lg border p-4"><h3 className="font-semibold">{editing?"Edit Teacher":"Add Teacher"}</h3>{([["name","Teacher name"],["phone","Phone number"],["email","Email"]] as const).map(([key,label])=><label key={key} className="block text-xs font-medium">{label}<input className="mt-1 h-9 w-full rounded border px-2 text-sm" value={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})}/></label>)}<label className="block text-xs font-medium">Department<select className="mt-1 h-9 w-full rounded border px-2 text-sm" value={draft.departmentId} onChange={e=>setDraft({...draft,departmentId:e.target.value})}><option value="">Select department</option>{departments.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><div className="flex gap-2"><Button size="sm" onClick={save}><Plus className="mr-1 h-4 w-4"/>{editing?"Update":"Add Teacher"}</Button>{editing&&<Button size="sm" variant="outline" onClick={()=>{setEditing(null);setDraft(blank)}}>Cancel</Button>}</div>{message&&<p className="text-xs text-red-600">{message}</p>}</div><div><label className="relative block"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input className="h-10 w-full rounded border pl-10 text-sm" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search teacher, phone, email, or department..."/></label><div className="mt-3 overflow-auto rounded-lg border"><table className="w-full min-w-[700px] text-sm"><thead className="bg-slate-50 text-left text-xs text-slate-500"><tr>{["Teacher","Phone","Email","Department","Laptop Status","Actions"].map(x=><th key={x} className="p-3">{x}</th>)}</tr></thead><tbody>{shown.map(x=><tr key={x.id} className="border-t"><td className="p-3 font-medium">{x.name}</td><td className="p-3">{x.phone}</td><td className="p-3">{x.email}</td><td className="p-3">{x.department}</td><td className="p-3"><RentalStatus status={x.laptopStatus ?? "No Rental"}/></td><td className="p-3"><Button size="icon" variant="ghost" onClick={()=>{setEditing(x.id);setDraft({name:x.name,email:x.email,phone:x.phone,departmentId:String(x.departmentId)})}}><Pencil className="h-4 w-4"/></Button><Button size="icon" variant="ghost" className="text-red-600" onClick={()=>void remove(x.id)}><Trash2 className="h-4 w-4"/></Button></td></tr>)}{!shown.length&&<tr><td colSpan={6} className="p-10 text-center text-slate-500">No teachers yet.</td></tr>}</tbody></table></div></div></div></DialogContent></Dialog>;
function RentalStatus({status}:{status:string}) { const key=status.toLowerCase(); const style=key==='approved'||key==='issued'||key==='active'?'bg-green-50 text-green-700':key==='pending'?'bg-amber-50 text-amber-700':key==='returned'?'bg-slate-100 text-slate-700':key==='no rental'?'bg-slate-100 text-slate-600':'bg-red-50 text-red-700'; return <span className={'rounded-full px-2.5 py-1 text-xs font-medium '+style}>{status}</span>; }
}
